name: Run Backend and Frontend Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Docker Composeを使ってサービスをビルドし起動
      - name: Set up Docker Compose and Build Services
        run: docker-compose up --build -d

      # 3. Jestでバックエンドのテストを実行
      - name: Run Backend Jest Tests
        run: docker-compose exec backend npm run test

      # 4. Playwrightでフロントエンドのテストを実行
      - name: Run Frontend Playwright Tests
        run: docker-compose exec frontend npx playwright test

      # 5. テスト後にすべてのコンテナを停止
      - name: Stop Docker Compose
        run: docker-compose down
